tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "git"
brew "gitmoji"
brew "mas"
brew "neovim"
brew "starship"
cask "coteditor"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "iterm2-beta"
mas "Xcode", id: 497799835
